include/pando-lib-galois/sync/global_barrier.hpp
test/sync/CMakeLists.txt
test/sync/test_global_barrier.cpp

Global Barrier implementation and test cases

---

test/sync/test_simple_lock.cpp

I made a small mistake we didn't catch.

Fix simplelock test

---

include/pando-lib-galois/graphs/dist_array_csr.hpp
include/pando-lib-galois/import/ingest_rmat_el.hpp
src/ingest_rmat_el.cpp
test/graphs/test_dist_array_csr.cpp
test/utility/test_gptr_monad.cpp

Add `InitializeELDACSR`, where can read in RMAT EL into a DistArrayCSR

Add InitializeELDACSR (Need for TC)

---

include/pando-lib-galois/graphs/local_csr.hpp
include/pando-lib-galois/utility/counted_iterator.hpp

- Add `iterator_offset` to Vertex
- Add more comparator operators to CountedIterator

Add utils needed for chunked TC.

---

include/pando-lib-galois/graphs/dist_local_csr.hpp
include/pando-lib-galois/graphs/local_csr.hpp

Add localVertices and edges with windowsz and offset so can get subranges of the vertices and edges

Add methods for graph subranges (needed for TC)

---

include/pando-lib-galois/import/ingest_rmat_el.hpp
src/ingest_rmat_el.cpp
test/import/test_wmd_importer.cpp

- Update initializeELDACSR to use ThreadLocalVector
- Update `initializeELDLCSR` test to deinitialize filename

Update initializeELDACSR to use ThreadLocalVector

---

CMakeLists.txt
microbench/CMakeLists.txt
microbench/triangle-counting/CMakeLists.txt
microbench/triangle-counting/Readme.md
microbench/triangle-counting/docs/CMakeLists.txt
microbench/triangle-counting/include/utils.hpp
microbench/triangle-counting/src/CMakeLists.txt
microbench/triangle-counting/src/bench_remote_access.cpp
microbench/triangle-counting/src/utils.cpp
microbench/triangle-counting/test/CMakeLists.txt

- Add microbench folder and simple microbench for remote accesses

Add microbench folder and simple microbench for remote accesses

---

graphs/rmat_571919_seed1_scale5_nV32_nE153.el
microbench/triangle-counting/CMakeLists.txt
microbench/triangle-counting/Readme.md
microbench/triangle-counting/include/tc_algos.hpp
microbench/triangle-counting/include/utils.hpp
microbench/triangle-counting/src/CMakeLists.txt
microbench/triangle-counting/src/graph_compare.cpp
microbench/triangle-counting/src/tc.cpp
microbench/triangle-counting/src/tc_algos.cpp
microbench/triangle-counting/src/utils.cpp
microbench/triangle-counting/test/CMakeLists.txt
microbench/triangle-counting/test/test_tc.cpp

Add non-chunk basic TC

---

microbench/triangle-counting/include/utils.hpp
microbench/triangle-counting/src/tc_algos.cpp
microbench/triangle-counting/src/utils.cpp

Add TC Chunked Vertices

---

microbench/CPPLINT.cfg
microbench/triangle-counting/Readme.md
microbench/triangle-counting/include/tc_algos.hpp
microbench/triangle-counting/include/utils.hpp
microbench/triangle-counting/src/tc_algos.cpp
microbench/triangle-counting/src/utils.cpp

TC Chunked Edges

---

include/pando-lib-galois/import/ingest_rmat_el.hpp
test/python/test_MDLCSR_Broadcast.cpp
test/python/test_MDLCSR_MapExchange.cpp
test/python/test_MDLCSR_Reduce.cpp
test/python/test_MDLCSR_Sync.cpp

fix MDLCSR test and clean up ELVertex

---

include/pando-lib-galois/graphs/mirror_dist_local_csr.hpp
microbench/bfs/include/pando-bfs-galois/sssp.hpp
microbench/bfs/src/main.cpp
scripts/prep_access_count/trace_process.py
test/python/test_MDLCSR_Broadcast.cpp
test/python/test_MDLCSR_Reduce.cpp
test/python/test_MDLCSR_Sync.cpp

BFS optimization and memory access count script update

---

scripts/prep_access_count/trace_process.py

slight access count script update

---

include/pando-lib-galois/sync/simple_lock.hpp
microbench/bfs/src/sssp.cpp
pando-rt/include/pando-rt/memory/common_memory_resource.hpp
pando-rt/include/pando-rt/memory/slab_memory_resource.hpp
pando-rt/include/pando-rt/sync/atomic.hpp
pando-rt/include/pando-rt/sync/mutex.hpp
pando-rt/src/atomic.cpp
pando-rt/test/sync/test_atomics.cpp
src/atomic.cpp

Atomic operations interface cleanup & atomicCompareExchange function fix

---

pando-drv/api/DrvAPIMemory.hpp
pando-drv/element/DrvCore.cpp
pando-drv/tests/drv.py
pando-drv/tests/drv_memory.py
pando-drv/tests/drv_pandohammer.py
pando-drv/tests/drv_tile.py
pando-rt/cmake/PANDOCompilerOptions.cmake
pando-rt/include/pando-rt/memory/global_ptr.hpp
pando-rt/src/drvx/CMakeLists.txt
pando-rt/src/global_ptr.cpp

Load / Store the whole object at once instead of every 8 bytes to speed things up

---

examples/CMakeLists.txt
examples/benchmark_loadbalance.cpp
include/pando-lib-galois/loops/do_all.hpp
pando-rt/include/pando-rt/benchmark/counters.hpp
pando-rt/src/init.cpp
pando-rt/src/prep/cores.cpp
pando-rt/src/start.cpp

DO NOT MERGE THIS PR, it is for CI only right now.

DoAll using Random Policy internally

---

include/pando-lib-galois/graphs/mirror_dist_local_csr.hpp

Speed up MDLCSR functions a bit

---

docs/DRVX.md
microbench/bfs/include/pando-bfs-galois/sssp.hpp
microbench/bfs/src/main.cpp
pando-rt/cmake/PANDOCompilerOptions.cmake
pando-rt/include/pando-rt/drv_info.hpp
pando-rt/include/pando-rt/memory/global_ptr.hpp
pando-rt/src/atomic.cpp
pando-rt/src/drv_info.cpp
pando-rt/src/drvx/CMakeLists.txt
pando-rt/src/drvx/cores.cpp
pando-rt/src/drvx/cp.cpp
pando-rt/src/global_ptr.cpp

Bypass graph import SST simulation in DrvX

---

include/pando-lib-galois/sync/global_barrier.hpp
include/pando-lib-galois/sync/wait_group.hpp
pando-drv/api/DrvAPIMemory.hpp
pando-drv/api/DrvAPIThreadState.hpp
pando-drv/element/DrvCore.hpp
pando-drv/element/DrvCustomStdMem.cpp
pando-drv/element/DrvCustomStdMem.hpp
pando-drv/element/DrvStdMemory.cpp
pando-rt/include/pando-rt/execution/execute_on_wait.hpp
pando-rt/include/pando-rt/execution/result_storage.hpp
pando-rt/include/pando-rt/sync/future.hpp
pando-rt/include/pando-rt/sync/notification.hpp
pando-rt/include/pando-rt/sync/wait.hpp
sst-elements-src/src/sst/elements/memHierarchy/customcmd/customCmdMemory.h
sst-elements-src/src/sst/elements/memHierarchy/customcmd/defCustomCmdHandler.cc
sst-elements-src/src/sst/elements/memHierarchy/customcmd/defCustomCmdHandler.h
sst-elements-src/src/sst/elements/memHierarchy/memoryController.cc
sst-elements-src/src/sst/elements/memHierarchy/memoryController.h

Creates an API in DrvX that can monitor a memory address until the value equals a certain value.

Monitor a memory address until it reaches or is no longer a certain value in Drv X 

---

microbench/bfs/src/main.cpp
pando-rt/include/pando-rt/drv_info.hpp

Example to expose current DrvX cycle time in the application program

example to print out current cycles
